(() => {
'use strict';
const $=id=>document.getElementById(id);
const STORE='photoia-ai-studio-v2';
const state={main:null,reference:null,controller:null,history:[],settings:{url:'',token:''},online:false,mode:'image_edit'};
function app(){return window.PhotoIA}
function toast(m){app()?.toast?.(m)}
function read(){try{const x=JSON.parse(localStorage.getItem(STORE)||'{}');state.settings={...state.settings,...(x.settings||{})};state.history=Array.isArray(x.history)?x.history.slice(0,8):[]}catch{}}
function save(){localStorage.setItem(STORE,JSON.stringify({settings:state.settings,history:state.history.slice(0,8)}))}
function setBadge(mode,text){const el=$('ai-server-badge');el.className=`ai-server-badge ${mode}`;el.innerHTML=`<i></i>${text}`;state.online=mode==='online'}
function setStatus(mode,title,detail,pct=0){const box=$('ai-job-status');box.className=`ai-job-status ${mode}`;box.querySelector('strong').textContent=title;box.querySelector('small').textContent=detail;$('ai-progress-text').textContent=`${Math.round(pct)}%`;$('ai-progress-bar').style.width=`${Math.max(0,Math.min(100,pct))}%`}
function dataUrlToBlob(data){const [head,b64]=data.split(',');const mime=(head.match(/:(.*?);/)||[])[1]||'image/jpeg';const bin=atob(b64);const arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type:mime})}
function preview(id,source,emptyIcon,emptyText){const box=$(id);box.innerHTML='';if(source){const img=document.createElement('img');img.src=source instanceof File?URL.createObjectURL(source):source;box.appendChild(img)}else box.innerHTML=`<b>${emptyIcon}</b><small>${emptyText}</small>`}
function canvasImage(){try{return app()?.exportDataUrl?.()||''}catch{return ''}}
function useCanvas(){const d=canvasImage();if(!d)return toast('Abre una foto primero.');state.main=d;preview('ai-main-preview',d,'📷','Usar foto del lienzo');toast('Foto del lienzo preparada')}
function chooseFile(input,key,previewId){const f=input.files?.[0];if(!f)return;state[key]=f;preview(previewId,f,key==='main'?'📷':'＋',key==='main'?'Foto principal':'Referencia');if(key==='reference')$('ai-clear-reference').disabled=false}
function renderHistory(){const wrap=$('ai-history');wrap.innerHTML='';if(!state.history.length){wrap.innerHTML='<p class="layers-empty">Todavía no hay resultados del Estudio IA.</p>';return}state.history.forEach((item,i)=>{const d=document.createElement('div');d.className='ai-history-item';d.innerHTML=`<img alt="Resultado IA ${i+1}" src="${item.image}"><button type="button">Usar resultado</button>`;d.querySelector('button').onclick=async()=>{await app()?.setMainImage?.(item.image,'Resultado Estudio IA');toast('Resultado colocado en el lienzo')};wrap.appendChild(d)})}
async function testConnection(){const raw=$('ai-server-url').value.trim().replace(/\/$/,'');if(!raw){setBadge('offline','Falta dirección');return toast('Escribe la dirección del servidor.')}setBadge('testing','Probando…');$('ai-connection-note').textContent='Buscando Photoshop AI Server…';const c=new AbortController();const timer=setTimeout(()=>c.abort(),5000);try{const r=await fetch(`${raw}/health`,{headers:state.settings.token?{'X-PhotoIA-Token':state.settings.token}:{},signal:c.signal,cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const info=await r.json().catch(()=>({}));const ready=info.ready!==false;setBadge(ready?'online':'testing',ready?'PC lista':'Falta configurar');$('ai-connection-note').textContent=`Conectada${info.gpu?` • ${info.gpu}`:''}${info.model?` • ${info.model}`:''}${info.workflowReady===false?' • Falta workflow API':''}`;state.online=ready;toast(ready?'Alienware conectado':'Servidor conectado; falta terminar el workflow')}catch(e){setBadge('offline','PC desconectada');$('ai-connection-note').textContent='No se encontró el servidor. Es normal si el Alienware está apagado o estás fuera de casa.';toast('Servidor no disponible')}finally{clearTimeout(timer)}}
function saveSettings(){state.settings.url=$('ai-server-url').value.trim().replace(/\/$/,'');state.settings.token=$('ai-server-token').value.trim();save();toast('Conexión guardada')}
async function sourceBlob(source){if(source instanceof File)return source;if(typeof source==='string'&&source.startsWith('data:'))return dataUrlToBlob(source);throw new Error('No hay fotografía principal.')}
async function generate(){const prompt=$('ai-prompt').value.trim();if(!prompt)return toast('Escribe qué quieres hacer.');if(!state.main){const d=canvasImage();if(d)state.main=d}if(!state.main)return toast('Agrega una fotografía principal.');saveSettings();if(!state.settings.url){setStatus('error','Tarea preparada','Guarda la dirección del Alienware cuando estés en casa.',0);return toast('La tarea está lista, pero falta configurar el servidor.')}if(!state.online){await testConnection();if(!state.online){setStatus('error','Alienware no disponible','Enciende la PC y el servidor para enviar esta tarea.',0);return}}
 state.controller=new AbortController();$('ai-generate').disabled=true;$('ai-cancel-job').hidden=false;setStatus('processing','Enviando fotografías','Preparando la tarea para FLUX.2 Klein…',12);
 try{const form=new FormData();form.append('prompt',prompt);form.append('mode',state.reference&&state.mode==='image_edit'?'multi_reference_edit':state.mode||'image_edit');form.append('profile','smart_edit');form.append('image',await sourceBlob(state.main),'main.jpg');if(state.reference)form.append('reference',await sourceBlob(state.reference),'reference.jpg');
 const progress=setInterval(()=>{const current=parseInt($('ai-progress-text').textContent)||12;if(current<88)setStatus('processing','Procesando en Alienware','FLUX.2 Klein está creando la edición…',current+Math.random()*5)},1200);
 const r=await fetch(`${state.settings.url}/api/v1/edit`,{method:'POST',headers:state.settings.token?{'X-PhotoIA-Token':state.settings.token}:{},body:form,signal:state.controller.signal});clearInterval(progress);if(!r.ok){let msg='';try{msg=(await r.json()).error||''}catch{}throw new Error(msg||`Error ${r.status}`)}
 const type=r.headers.get('content-type')||'';let result;if(type.includes('application/json')){const j=await r.json();result=j.image||j.dataUrl||j.result;if(result&&!result.startsWith('data:')&&!result.startsWith('http'))result=`data:image/png;base64,${result}`}else{const blob=await r.blob();result=await new Promise((ok,no)=>{const fr=new FileReader();fr.onload=()=>ok(fr.result);fr.onerror=no;fr.readAsDataURL(blob)})}
 if(!result)throw new Error('El servidor no devolvió una imagen.');setStatus('done','Edición terminada','El resultado se colocó en el lienzo.',100);state.history.unshift({image:result,prompt,date:Date.now()});state.history=state.history.slice(0,8);save();renderHistory();await app()?.setMainImage?.(result,'Resultado Estudio IA');toast('Edición recibida del Alienware')
 }catch(e){if(e.name==='AbortError')setStatus('error','Tarea cancelada','No se aplicaron cambios.',0);else{setStatus('error','No se pudo completar',e.message||'Error desconocido.',0);toast(e.message||'Error del servidor')}}finally{$('ai-generate').disabled=false;$('ai-cancel-job').hidden=true;state.controller=null}}
function init(){read();$('ai-server-url').value=state.settings.url;$('ai-server-token').value=state.settings.token;renderHistory();
 $('ai-use-canvas').onclick=useCanvas;$('ai-choose-main').onclick=()=>$('ai-main-file').click();$('ai-main-file').onchange=e=>chooseFile(e.target,'main','ai-main-preview');$('ai-choose-reference').onclick=()=>$('ai-reference-file').click();$('ai-reference-file').onchange=e=>chooseFile(e.target,'reference','ai-reference-preview');$('ai-clear-reference').onclick=()=>{state.reference=null;$('ai-reference-file').value='';preview('ai-reference-preview',null,'＋','Persona, ropa o estilo');$('ai-clear-reference').disabled=true};
 document.querySelectorAll('[data-ai-action]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-ai-action]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.aiMode||'image_edit';$('ai-prompt').value=b.dataset.aiAction;$('ai-prompt').focus();toast(`Modo inteligente: ${b.textContent.trim()}`)});
 $('ai-save-settings').onclick=saveSettings;$('ai-test-server').onclick=async()=>{saveSettings();await testConnection()};$('ai-generate').onclick=generate;$('ai-cancel-job').onclick=async()=>{state.controller?.abort();try{if(state.settings.url)await fetch(`${state.settings.url}/api/v1/interrupt`,{method:'POST',headers:state.settings.token?{'X-PhotoIA-Token':state.settings.token}:{}})}catch{}};$('ai-clear-history').onclick=()=>{state.history=[];save();renderHistory();toast('Historial del Estudio IA limpiado')};
 window.addEventListener('photoia-ready',()=>{if(app()?.state?.photo&&!state.main)useCanvas()},{once:true});if(state.settings.url)testConnection();}
document.addEventListener('DOMContentLoaded',init);
})();
