'use strict';
const $=id=>document.getElementById(id), canvas=$('editor-canvas'), ctx=canvas.getContext('2d',{willReadFrequently:true});
let sourceImage=null,rotation=0,flipX=false,squareCrop=false,compareDown=false,history=[],historyIndex=-1,renderTimer=0;
const sliders=['brightness','contrast','saturation','temperature','sharpness','blur'];
const controls=[...document.querySelectorAll('button[data-preset],button[data-command],button[data-studio],.slider-list input,#rotate-left,#rotate-right,#flip-x,#crop-square,#reset-btn,#compare-btn,#download-btn,#command-input,#command-btn')];
const studioData={
 magic:{title:'One Click Magic',desc:'Analiza la foto con reglas locales y aplica una mejora equilibrada.',options:[['✨','Mejora profesional','Color, contraste y nitidez','local','auto'],['🙂','Retrato natural','Tonos más suaves','local','portrait'],['🌈','Color vibrante','Más fuerza sin exagerar','local','vivid']]},
 outfit:{title:'Outfit Studio',desc:'Arquitectura preparada para cambiar ropa conservando pose, cuerpo y rostro.',options:[['👔','Traje elegante','Negro, azul o gris','IA'],['🧥','Chaqueta','Cuero, denim o casual','IA'],['🏭','Uniforme industrial','Casco, chaleco y uniforme','IA'],['🦸','Disfraces y personajes','Para ediciones divertidas','IA']]},
 hair:{title:'Hair Studio',desc:'Peinados, color, barba y cambios de apariencia.',options:[['💇','Cambiar peinado','Corto, largo, rizado o liso','IA'],['🎨','Cambiar color','Rubio, negro, rojo o fantasía','IA'],['🧔','Barba y bigote','Agregar, quitar o cambiar estilo','IA'],['✨','Reflejos','Mechas y tonos selectivos','IA']]},
 face:{title:'Face Studio',desc:'Retoques y transformaciones faciales para uso personal y creativo.',options:[['😁','Sonrisa','Cambiar expresión','IA'],['🕰️','Edad','Rejuvenecer o envejecer','IA'],['💄','Retoque natural','Piel, ojos y dientes','IA'],['👓','Accesorios','Lentes, sombreros y joyería','IA']]},
 swap:{title:'Fun Swap',desc:'Intercambia caras o cuerpos entre personas de una fotografía.',options:[['🔄','Face Swap','Intercambiar rostros','IA'],['🕺','Body Swap','Intercambiar cuerpos','IA'],['🎭','Cambio de cabeza','Colocar una cabeza en otro cuerpo','IA'],['🎲','Surprise Me','Una transformación al azar','IA']]},
 background:{title:'Background Studio',desc:'Herramientas para modificar el fondo.',options:[['🫥','Quitar fondo','Crear transparencia','IA'],['🌫️','Desenfocar todo','Desenfoque local rápido','local','blur'],['🌅','Cambiar escenario','Playa, ciudad o estudio','IA'],['🎨','Color sólido','Fondo limpio de estudio','IA']]},
 design:{title:'Text & Design',desc:'Herramientas visuales sin necesidad de experiencia.',options:[['🔤','Agregar texto','Próximo módulo local','next'],['😊','Stickers','Próximo módulo local','next'],['✏️','Dibujar','Próximo módulo local','next'],['🖼️','Marco','Próximo módulo local','next']]},
 repair:{title:'Magic Repair',desc:'Limpieza, restauración y borrado inteligente.',options:[['🧽','Borrar objeto','Relleno inteligente','IA'],['🩹','Healing Brush','Reparar pequeñas áreas','next'],['🕰️','Restaurar foto vieja','Ruido, contraste y daños','IA'],['🔍','Aumentar resolución','Upscale inteligente','IA']]}
};
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1900)}
function values(){return Object.fromEntries(sliders.map(id=>[id,Number($(id).value)]))}
function setEnabled(enabled){controls.forEach(el=>el.disabled=!enabled);$('undo-btn').disabled=!enabled||historyIndex<=0;$('redo-btn').disabled=!enabled||historyIndex>=history.length-1}
function snapshot(){return {filters:values(),rotation,flipX,squareCrop}}
function applySnapshot(s){sliders.forEach(id=>{$(id).value=s.filters[id];$(id+'-out').value=s.filters[id]});rotation=s.rotation;flipX=s.flipX;squareCrop=s.squareCrop;render()}
function commit(){history=history.slice(0,historyIndex+1);history.push(JSON.parse(JSON.stringify(snapshot())));historyIndex=history.length-1;setEnabled(true)}
function loadFile(file){if(!file||!file.type.startsWith('image/'))return toast('Selecciona una imagen válida.');const reader=new FileReader();reader.onload=e=>{const img=new Image();img.onload=()=>{sourceImage=img;rotation=0;flipX=false;squareCrop=false;sliders.forEach(id=>{$(id).value=0;$(id+'-out').value=0});history=[];historyIndex=-1;commit();$('empty-state').hidden=true;canvas.style.display='block';$('project-title').textContent=file.name||'Foto';$('image-info').textContent=`${img.naturalWidth} × ${img.naturalHeight}`;render();toast('Foto abierta');};img.src=e.target.result};reader.readAsDataURL(file)}
function dimensions(){let w=sourceImage.naturalWidth,h=sourceImage.naturalHeight;if(squareCrop){const s=Math.min(w,h);w=h=s}if(Math.abs(rotation)%180===90)[w,h]=[h,w];const max=1800,scale=Math.min(1,max/Math.max(w,h));return{w:Math.round(w*scale),h:Math.round(h*scale)}}
function render(useOriginal=false){if(!sourceImage)return;cancelAnimationFrame(renderTimer);renderTimer=requestAnimationFrame(()=>{const d=dimensions();canvas.width=d.w;canvas.height=d.h;ctx.save();ctx.clearRect(0,0,d.w,d.h);ctx.translate(d.w/2,d.h/2);ctx.rotate(rotation*Math.PI/180);ctx.scale(flipX?-1:1,1);let sw=sourceImage.naturalWidth,sh=sourceImage.naturalHeight,sx=0,sy=0;if(squareCrop){const s=Math.min(sw,sh);sx=(sw-s)/2;sy=(sh-s)/2;sw=sh=s}const rotated=Math.abs(rotation)%180===90,dw=rotated?d.h:d.w,dh=rotated?d.w:d.h,f=useOriginal?{brightness:0,contrast:0,saturation:0,temperature:0,sharpness:0,blur:0}:values();ctx.filter=`brightness(${100+f.brightness}%) contrast(${100+f.contrast}%) saturate(${100+f.saturation}%) blur(${f.blur}px)`;ctx.drawImage(sourceImage,sx,sy,sw,sh,-dw/2,-dh/2,dw,dh);ctx.restore();if(!useOriginal&&f.temperature)applyTemperature(f.temperature);if(!useOriginal&&f.sharpness)applySharpen(f.sharpness/100)})}
function applyTemperature(amount){const im=ctx.getImageData(0,0,canvas.width,canvas.height),a=im.data,shift=amount*.65;for(let i=0;i<a.length;i+=4){a[i]=Math.max(0,Math.min(255,a[i]+shift));a[i+2]=Math.max(0,Math.min(255,a[i+2]-shift))}ctx.putImageData(im,0,0)}
function applySharpen(strength){const im=ctx.getImageData(0,0,canvas.width,canvas.height),src=im.data,out=new Uint8ClampedArray(src),w=canvas.width,h=canvas.height,s=Math.min(.8,strength*.8);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4;for(let c=0;c<3;c++){const center=src[i+c]*5-src[i-4+c]-src[i+4+c]-src[i-w*4+c]-src[i+w*4+c];out[i+c]=src[i+c]*(1-s)+center*s}}im.data.set(out);ctx.putImageData(im,0,0)}
function preset(name){const p={auto:[10,12,10,4,18,0],professional:[10,14,12,3,20,0],portrait:[8,-2,-5,5,8,1],vivid:[6,18,28,3,14,0],bw:[5,15,-100,0,12,0]}[name]||[0,0,0,0,0,0];sliders.forEach((id,i)=>{$(id).value=p[i];$(id+'-out').value=p[i]});commit();render();toast('Ajuste aplicado')}
function executeCommand(raw){const q=raw.toLowerCase().trim();if(!q)return toast('Escribe lo que quieres hacer.');if(/profesional|mejorar|autom[aá]tic/.test(q))return preset('professional');if(/retrato|piel|cara/.test(q))return preset('portrait');if(/vibrante|m[aá]s color|satur/.test(q))return preset('vivid');if(/blanco|negro|monocrom/.test(q))return preset('bw');if(/brillante|aclar/.test(q)){sliders.forEach(id=>{});$('brightness').value=25;$('brightness-out').value=25;commit();render();return toast('Foto aclarada')};if(/oscura|bajar brillo/.test(q)){$('brightness').value=-20;$('brightness-out').value=-20;commit();render();return toast('Brillo reducido')};if(/desenfoc/.test(q)){$('blur').value=6;$('blur-out').value=6;commit();render();return toast('Desenfoque aplicado')};if(/ropa|pelo|cabello|cuerpo|face swap|cara en|fondo|borrar/.test(q))return toast('Esa transformación usará el módulo de IA generativa. La interfaz ya está preparada.');toast('Todavía no reconozco esa instrucción. Prueba “hazla profesional”.')}
function openStudio(key){const data=studioData[key];if(!data)return;$('sheet-title').textContent=data.title;$('sheet-description').textContent=data.desc;$('sheet-content').innerHTML='';data.options.forEach(([icon,title,sub,type,action])=>{const b=document.createElement('button');b.className='sheet-option';b.innerHTML=`<span>${icon}</span><div><strong>${title}</strong><small>${sub}</small></div><em class="badge">${type==='local'?'LOCAL':type==='next'?'PRÓXIMO':'IA'}</em>`;b.onclick=()=>{if(type==='local'){if(action==='blur'){$('blur').value=6;$('blur-out').value=6;commit();render();toast('Desenfoque aplicado')}else preset(action);closeSheet()}else toast(type==='next'?'Se añadirá como herramienta local en la próxima actualización.':'Esta opción necesita conectar el motor de IA generativa.')};$('sheet-content').appendChild(b)});$('studio-sheet').hidden=false}
function closeSheet(){$('studio-sheet').hidden=true}
sliders.forEach(id=>{$(id).addEventListener('input',()=>{$(id+'-out').value=$(id).value;render()});$(id).addEventListener('change',commit)});document.querySelectorAll('button[data-preset]').forEach(b=>b.onclick=()=>preset(b.dataset.preset));document.querySelectorAll('button[data-command]').forEach(b=>b.onclick=()=>executeCommand(b.dataset.command));document.querySelectorAll('button[data-studio]').forEach(b=>b.onclick=()=>openStudio(b.dataset.studio));
$('command-btn').onclick=()=>executeCommand($('command-input').value);$('command-input').addEventListener('keydown',e=>{if(e.key==='Enter')executeCommand(e.target.value)});$('file-input').onchange=e=>loadFile(e.target.files[0]);$('camera-input').onchange=e=>loadFile(e.target.files[0]);$('rotate-left').onclick=()=>{rotation=(rotation-90)%360;commit();render()};$('rotate-right').onclick=()=>{rotation=(rotation+90)%360;commit();render()};$('flip-x').onclick=()=>{flipX=!flipX;commit();render()};$('crop-square').onclick=()=>{squareCrop=!squareCrop;commit();render();toast(squareCrop?'Recorte cuadrado':'Recorte original')};$('reset-btn').onclick=()=>{sliders.forEach(id=>{$(id).value=0;$(id+'-out').value=0});rotation=0;flipX=false;squareCrop=false;commit();render();toast('Foto restablecida')};$('undo-btn').onclick=()=>{if(historyIndex>0){historyIndex--;applySnapshot(history[historyIndex]);setEnabled(true)}};$('redo-btn').onclick=()=>{if(historyIndex<history.length-1){historyIndex++;applySnapshot(history[historyIndex]);setEnabled(true)}};$('compare-btn').addEventListener('pointerdown',()=>{compareDown=true;render(true)});['pointerup','pointerleave','pointercancel'].forEach(ev=>$('compare-btn').addEventListener(ev,()=>{if(compareDown){compareDown=false;render()}}));$('download-btn').onclick=()=>{render();setTimeout(()=>{const format=$('format').value,q=Number($('quality').value)/100,ext=format==='image/png'?'png':format==='image/webp'?'webp':'jpg',a=document.createElement('a');a.download=`photo-ia-${Date.now()}.${ext}`;a.href=canvas.toDataURL(format,q);a.click();toast('Imagen guardada')},80)};$('theme-btn').onclick=()=>{document.documentElement.classList.toggle('dark');localStorage.setItem('photoIATheme',document.documentElement.classList.contains('dark')?'dark':'light')};$('sheet-close').onclick=closeSheet;$('sheet-backdrop').onclick=closeSheet;
if(localStorage.getItem('photoIATheme')==='dark')document.documentElement.classList.add('dark');setEnabled(false);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
