(() => {
'use strict';
const VERSION='13.1-photo-critic-engine';
const $=id=>document.getElementById(id),api=()=>window.PhotoIA,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let lastAnalysis=null,lastAppliedSignature='';
function status(t,c='ready'){const b=$('smart-core-badge');if(b){b.textContent=t;b.className=`smart-core-badge ${c}`}}
function ensure(){if(!api()?.state?.photo)throw new Error('Abre una foto primero.');}
function adaptiveStrength(cv){const h=cv.histogram||{},r=cv.regions||{};let need=0;need+=clamp(Math.abs(132-(h.p50??cv.brightness))/120,0,.25);need+=clamp((52-cv.contrast)/130,0,.12);need+=clamp(cv.noiseEstimate/110,0,.10);need+=cv.blurRisk==='high'?.10:cv.blurRisk==='medium'?.05:.01;need+=cv.clipping?.white?.03:0;need+=cv.clipping?.black?.04:0;return +clamp(.34+need,r.face>.02?.34:.38,r.face>.02?.66:.78).toFixed(2)}
function buildRecipe(cv,critic){const h=cv.histogram||{},r=cv.regions||{},mid=h.p50??cv.brightness,strength=adaptiveStrength(cv),portrait=r.face>.02||r.skin>.035;
 const faceDark=critic.issues.some(x=>x.code==='face-dark'),skinHarsh=critic.issues.some(x=>x.code==='skin-harsh');
 const exposure=clamp(Math.log2((portrait?128:136)/Math.max(58,mid)),-.12,portrait?.22:.30)*strength;
 const shadows=clamp(Math.round((70-(h.p05||30))*(portrait?.20:.29)*strength)+(faceDark?5:0),0,portrait?18:25);
 const highlights=clamp(Math.round(((h.p95||220)-219)*(portrait?.25:.38)*strength),0,portrait?14:24);
 const contrast=portrait?clamp(Math.round((50-cv.contrast)*.12*strength),-3,5):clamp(Math.round((56-cv.contrast)*.22*strength),-3,12);
 return{exposure:+exposure.toFixed(2),shadows,highlights,contrast,vibrance:portrait?3:Math.round(7+strength*4),warmth:portrait?1:0,clarity:portrait?0:(cv.blurRisk==='high'?7:cv.blurRisk==='medium'?4:2),blackPoint:clamp(Math.round((h.p05||0)*(portrait?.06:.12)*strength),0,portrait?3:7),whitePoint:clamp(Math.round(255-(255-(h.p95||245))*.10),245,255),gamma:1,denoise:cv.noiseEstimate>18?6:cv.noiseEstimate>11?3:1,adaptiveStrength:skinHarsh?Math.min(strength,.52):strength,portraitProtection:portrait,faceLift:faceDark};}
function scene(cv){const r=cv.regions||{};if(r.face>.02)return r.green>.08?'Retrato en naturaleza':'Retrato';if(r.green>.14)return'Naturaleza';if(r.sky>.10)return'Exterior';if(cv.brightness<90)return'Poca luz';return'General'}
function quality(cv,recipe){let score=96;score-=cv.clipping?.white?3:0;score-=cv.clipping?.black?3:0;score-=recipe.adaptiveStrength>.72?2:0;score-=cv.blurRisk==='high'?3:0;return clamp(Math.round(score),75,97)}
async function analyze(){ensure();status('Analizando la fotografía con criterio profesional…','working');const el=$('smart-analysis-result');if(el)el.innerHTML='<div class="smart-progress-list"><span>✓ Leyendo la foto original</span><span>✓ Evaluando luz y color</span><span>✓ Protegiendo piel y rasgos</span><span>✓ Comparando sujeto y fondo</span><span>✓ Buscando errores que no deben empeorar</span><span class="working">● Diseñando la mejor edición…</span></div>';
 const cv=window.PhotoOpenCV?.ready?await window.PhotoOpenCV.analyzeCurrent('original'):null;if(!cv)throw new Error('OpenCV no está listo.');const critic=window.PhotoOpenCV.critiquePhoto(cv),sc=scene(cv),recipe=buildRecipe(cv,critic),confidence=quality(cv,recipe);lastAnalysis={opencv:cv,critic,scene:sc,recommendation:recipe,recipeName:sc.startsWith('Retrato')?'Retrato natural protegido':'Mejora natural inteligente',confidence,at:Date.now()};render(lastAnalysis);status('Análisis profesional listo','ready');return lastAnalysis}
function render(a){const e=$('smart-analysis-result');if(!e)return;const c=a.opencv,r=c.regions||{},regions=c.detectedRegions?.length?c.detectedRegions.join(' · '):'General',intensity=Math.round(a.recommendation.adaptiveStrength*100),issues=a.critic.issues.map(x=>`<li><strong>${x.label}</strong><span>${x.advice}</span></li>`).join('');e.innerHTML=`<div class="smart-pro-result"><div class="smart-pro-title"><strong>⭐ ${a.recipeName}</strong><small>${a.confidence}% confianza</small></div><div class="smart-metrics smart-metrics-six"><div><small>Escena</small><strong>${a.scene}</strong></div><div><small>Regiones</small><strong>${regions}</strong></div><div><small>Intensidad</small><strong>${intensity}%</strong></div><div><small>Enfoque</small><strong>${c.blurRisk==='low'?'Bueno':c.blurRisk==='medium'?'Medio':'Bajo'}</strong></div><div><small>Ruido</small><strong>${c.noiseEstimate}</strong></div><div><small>Piel protegida</small><strong>${r.face>.02?'Sí':'No aplica'}</strong></div></div><p>${a.critic.summary}</p>${issues?`<ul class="photo-critic-list">${issues}</ul>`:''}<p><strong>Regla:</strong> no resaltar manchas, poros o arrugas y no alterar una zona que ya está bien.</p></div>`;if($('smart-apply'))$('smart-apply').disabled=false}
function signature(a){return JSON.stringify({at:a.at,recipe:a.recommendation,original:api().state.originalDataUrl?.slice(-48)})}
async function apply(btn){btn.disabled=true;const old=btn.textContent;btn.textContent='Pensando y aplicando la mejor edición…';status('Procesando desde la foto original…','working');try{const a=lastAnalysis||await analyze(),sig=signature(a);if(sig===lastAppliedSignature){api().toast('La mejor mejora ya está aplicada.');status('Mejora ya aplicada','ready');return}const data=await window.PhotoOpenCV.enhanceCurrent(a.recommendation,a.opencv,'original');await api().applyProcessedImageDataUrl(data,true);lastAppliedSignature=sig;renderRecipe(a);api().toast('Mejora natural aplicada sin acumular filtros');status('Mejora profesional aplicada','ready')}finally{btn.textContent=old;btn.disabled=false}}
function renderRecipe(a){const e=$('smart-recipe-result');if(!e)return;const r=a.opencv.regions||{},x=a.recommendation;e.hidden=false;e.innerHTML=`<div class="smart-recipe-head"><strong>${a.recipeName}</strong><small>${a.scene} · ${a.confidence}% confianza</small></div><div class="smart-recipe-values"><div><span>Fuerza</span><strong>${Math.round(x.adaptiveStrength*100)}%</strong></div><div><span>Piel</span><strong>${r.face>.02?'Protegida':'No detectada'}</strong></div><div><span>Sombras</span><strong>+${x.shadows}</strong></div><div><span>Claridad facial</span><strong>0</strong></div><div><span>Filtros acumulados</span><strong>No</strong></div></div>`}
async function regionalEdit(region,options,label){ensure();status(`Editando solo ${label}…`,'working');const data=await window.PhotoOpenCV.adjustRegion(region,options);await api().applyProcessedImageDataUrl(data,true);api().toast(`${label} corregido; el resto de la foto se conservó`);status('Edición regional aplicada','ready');return true}
async function understand(raw){const t=String(raw||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
 if(/cara|rostro/.test(t)&&/(oscura|muy negra|sin luz|sombra)/.test(t))return regionalEdit('face',{exposure:.25,shadows:22,warmth:2,smooth:true,detail:4,strength:.78},'el rostro');
 if(/cara|rostro/.test(t)&&/(muy clara|quemada|brillante|sobreexpuesta)/.test(t))return regionalEdit('face',{exposure:-.18,shadows:-4,warmth:0,smooth:true,detail:2,strength:.75},'el rostro');
 if(/menos cansad|ojeras|cansad/.test(t))return regionalEdit('face',{exposure:.12,shadows:14,warmth:1,smooth:true,detail:3,strength:.68},'el rostro');
 if(/solo.*fondo|mejora.*fondo/.test(t))return regionalEdit('background',{exposure:.05,shadows:5,detail:5,strength:.62},'el fondo');
 if(/piel/.test(t)&&/(suav|manchas|arrugas|natural)/.test(t))return regionalEdit('skin',{exposure:.04,shadows:5,warmth:1,smooth:true,detail:0,strength:.64},'la piel');
 if(/identificacion|credencial|pasaporte|id photo/.test(t)){window.PhotoAIStudio?.enterPortraitIdMode?.();api().toast('Modo identificación preparado con la foto completa, sin máscara de busto.');return true}
 return false}
async function runRetouch(btn,label,work,success){ensure();if(!window.PhotoOpenCV?.ready)throw new Error('OpenCV no está listo.');btn.disabled=true;const old=btn.textContent;btn.textContent=label;status('Aplicando retoque localizado…','working');try{const data=await work();await api().applyProcessedImageDataUrl(data,true);api().toast(success);status('Retoque localizado aplicado','ready')}finally{btn.textContent=old;btn.disabled=false}}
function boot(){const a=$('smart-analyze'),b=$('smart-apply'),smooth=$('smart-smooth-skin'),blem=$('smart-remove-blemishes'),moles=$('smart-remove-moles'),slider=$('portrait-strength'),value=$('portrait-strength-value');const updateStrength=()=>{if(value&&slider)value.textContent=`${slider.value}%`};if(slider){slider.oninput=updateStrength;updateStrength()}if(a)a.onclick=()=>analyze().catch(e=>{console.error(e);status('Error de análisis','error');api()?.toast(e.message)});if(b)b.onclick=()=>apply(b).catch(e=>{console.error(e);status('Error al aplicar','error');api()?.toast(e.message)});if(smooth)smooth.onclick=()=>runRetouch(smooth,'Suavizando…',()=>window.PhotoOpenCV.smoothPortraitSkin(Number(slider?.value||35)/100),'Piel suavizada de forma natural').catch(e=>api()?.toast(e.message));if(blem)blem.onclick=()=>runRetouch(blem,'Limpiando…',()=>window.PhotoOpenCV.removeSkinSpots('blemish'),'Granitos y manchas pequeñas reducidos').catch(e=>api()?.toast(e.message));if(moles)moles.onclick=()=>runRetouch(moles,'Retirando…',()=>window.PhotoOpenCV.removeSkinSpots('mole'),'Lunares pequeños retirados').catch(e=>api()?.toast(e.message));const setRetouchDisabled=v=>[smooth,blem,moles].forEach(x=>{if(x)x.disabled=v});document.addEventListener('photoia:image-loaded',()=>{lastAnalysis=null;lastAppliedSignature='';if(b)b.disabled=true;setRetouchDisabled(false);status('Lista para análisis profesional','ready')});document.addEventListener('photoia:image-cleared',()=>{lastAnalysis=null;lastAppliedSignature='';if(b)b.disabled=true;setRetouchDisabled(true);status('Esperando foto…','ready')});window.PhotoSmartCore={version:VERSION,analyze,applyRecommendations:()=>apply(b),understand,regionalEdit};status('Photo Critic Engine listo','ready')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
