(() => {
'use strict';
const VERSION='15.33-photo-critic-resilient';
const $=id=>document.getElementById(id),api=()=>window.PhotoIA,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let lastAnalysis=null,lastAppliedSignature='';
function status(t,c='ready'){const b=$('smart-core-badge');if(b){b.textContent=t;b.className=`smart-core-badge ${c}`}}
function ensure(){if(!api()?.state?.photo)throw new Error('Abre una foto primero.');}
function adaptiveStrength(cv){const h=cv.histogram||{},r=cv.regions||{};let need=0;need+=clamp(Math.abs(132-(h.p50??cv.brightness))/120,0,.25);need+=clamp((52-cv.contrast)/130,0,.12);need+=clamp(cv.noiseEstimate/110,0,.10);need+=cv.blurRisk==='high'?.10:cv.blurRisk==='medium'?.05:.01;need+=cv.clipping?.white?.03:0;need+=cv.clipping?.black?.04:0;return +clamp(.34+need,r.face>.02?.34:.38,r.face>.02?.66:.78).toFixed(2)}
function buildRecipe(cv,critic){const h=cv.histogram||{},r=cv.regions||{},mid=h.p50??cv.brightness,strength=adaptiveStrength(cv),portrait=r.face>.02||r.skin>.035;const faceDark=critic.issues.some(x=>x.code==='face-dark'),skinHarsh=critic.issues.some(x=>x.code==='skin-harsh');const exposure=clamp(Math.log2((portrait?128:136)/Math.max(58,mid)),-.12,portrait?.22:.30)*strength;const shadows=clamp(Math.round((70-(h.p05||30))*(portrait?.20:.29)*strength)+(faceDark?5:0),0,portrait?18:25);const highlights=clamp(Math.round(((h.p95||220)-219)*(portrait?.25:.38)*strength),0,portrait?14:24);const contrast=portrait?clamp(Math.round((50-cv.contrast)*.12*strength),-3,5):clamp(Math.round((56-cv.contrast)*.22*strength),-3,12);return{exposure:+exposure.toFixed(2),shadows,highlights,contrast,vibrance:portrait?3:Math.round(7+strength*4),warmth:portrait?1:0,clarity:portrait?0:(cv.blurRisk==='high'?7:cv.blurRisk==='medium'?4:2),blackPoint:clamp(Math.round((h.p05||0)*(portrait?.06:.12)*strength),0,portrait?3:7),whitePoint:clamp(Math.round(255-(255-(h.p95||245))*.10),245,255),gamma:1,denoise:cv.noiseEstimate>18?6:cv.noiseEstimate>11?3:1,adaptiveStrength:skinHarsh?Math.min(strength,.52):strength,portraitProtection:portrait,faceLift:faceDark};}
function scene(cv){const r=cv.regions||{};if(r.face>.02)return r.green>.08?'Retrato en naturaleza':'Retrato';if(r.green>.14)return'Naturaleza';if(r.sky>.10)return'Exterior';if(cv.brightness<90)return'Poca luz';return'General'}
function quality(cv,recipe){let score=96;score-=cv.clipping?.white?3:0;score-=cv.clipping?.black?3:0;score-=recipe.adaptiveStrength>.72?2:0;score-=cv.blurRisk==='high'?3:0;return clamp(Math.round(score),75,97)}
function percentile(hist,total,p){let n=0;for(let i=0;i<256;i++){n+=hist[i];if(n>=total*p)return i;}return 255;}
function canvasFallbackAnalysis(canvas){
 const ctx=canvas.getContext('2d',{willReadFrequently:true}),{width:w,height:h}=canvas,img=ctx.getImageData(0,0,w,h).data,hist=new Uint32Array(256);let sum=0,sum2=0,noise=0,edges=0,skin=0,green=0,sky=0,samples=0;
 for(let y=0;y<h;y+=2)for(let x=0;x<w;x+=2){const i=(y*w+x)*4,r=img[i],g=img[i+1],b=img[i+2],lum=Math.round(.299*r+.587*g+.114*b);hist[lum]++;sum+=lum;sum2+=lum*lum;samples++;const max=Math.max(r,g,b),min=Math.min(r,g,b),isSkin=r>45&&g>28&&b>18&&(max-min)>10&&r>g*.94&&r>b*1.02;if(isSkin)skin++;if(g>r*1.05&&g>b*1.08&&g>55)green++;if(y<h*.65&&b>r*1.08&&b>g*.98&&b>70)sky++;if(x+2<w){const j=(y*w+x+2)*4,d=Math.abs(lum-(.299*img[j]+.587*img[j+1]+.114*img[j+2]));noise+=Math.min(30,d);if(d>24)edges++;}}
 const mean=sum/Math.max(1,samples),variance=sum2/Math.max(1,samples)-mean*mean,std=Math.sqrt(Math.max(0,variance)),p05=percentile(hist,samples,.05),p50=percentile(hist,samples,.5),p95=percentile(hist,samples,.95),p01=percentile(hist,samples,.01),p99=percentile(hist,samples,.99),edgeDensity=edges/Math.max(1,samples),noiseEstimate=noise/Math.max(1,samples)*.42,face=Math.min(.16,skin/Math.max(1,samples)*.62),regions={face,skin:skin/Math.max(1,samples),green:green/Math.max(1,samples),sky:sky/Math.max(1,samples),dark:0};
 return{version:'canvas-fallback',width:w,height:h,brightness:Math.round(mean),contrast:Math.round(std),histogram:{p01,p05,p25:percentile(hist,samples,.25),p50,p75:percentile(hist,samples,.75),p95,p99},dynamicRange:p95-p05,edgeDensity:+edgeDensity.toFixed(4),noiseEstimate:+noiseEstimate.toFixed(2),blurRisk:edgeDensity<.025?'high':edgeDensity<.055?'medium':'low',regions,detectedRegions:[face>.025?'Rostro/Piel':null,regions.sky>.07?'Cielo':null,regions.green>.08?'Vegetación':null].filter(Boolean),horizon:{angle:0,confidence:0},clipping:{black:p01<3,white:p99>252},fallback:true};
}
function localCritique(report){const h=report.histogram||{},r=report.regions||{},issues=[],strengths=[];if(r.face>.02){if((h.p50||report.brightness)<105)issues.push({code:'face-dark',label:'Rostro oscuro',advice:'Iluminar con cuidado sin quemar el fondo.'});if(report.contrast>72)issues.push({code:'skin-harsh',label:'Contraste fuerte en piel',advice:'Mantener textura natural.'});strengths.push('Piel/rostro probable');}if(report.clipping?.white)issues.push({code:'highlights',label:'Altas luces al límite',advice:'Recuperar luces.'});if(report.clipping?.black)issues.push({code:'shadows',label:'Sombras cerradas',advice:'Abrir sombras de forma selectiva.'});if(report.blurRisk==='high')issues.push({code:'soft-focus',label:'Enfoque bajo',advice:'Evitar sobre-enfocar piel.'});return{issues,strengths,summary:issues.length?`Encontré ${issues.length} oportunidad${issues.length===1?'':'es'} de mejora sin perjudicar la foto.`:'La foto ya está equilibrada; aplicaré una mejora ligera y natural.'};}
async function getAnalysisReport(){
 const cv=window.PhotoOpenCV;status('Preparando motor fotográfico…','working');
 if(cv?.ready||await cv?.whenReady?.(12000)){try{return await cv.analyzeCurrent('original')}catch(err){console.warn('[Smart] OpenCV analysis fallback',err)}}
 status('OpenCV sigue cargando; usando análisis local compatible…','working');const canvas=await api().getOriginalAnalysisCanvas(900);return canvasFallbackAnalysis(canvas);
}
async function analyze(){
 ensure();status('Analizando la fotografía con criterio profesional…','working');const el=$('smart-analysis-result');if(el)el.innerHTML='<div class="smart-progress-list"><span>✓ Leyendo la foto original</span><span>✓ Evaluando luz y color</span><span>✓ Protegiendo piel y rasgos</span><span>✓ Comparando sujeto y fondo</span><span class="working">● Diseñando la mejor edición…</span></div>';
 const report=await getAnalysisReport(),critic=window.PhotoOpenCV?.critiquePhoto?.(report)||localCritique(report),sc=scene(report),recipe=buildRecipe(report,critic),confidence=quality(report,recipe);lastAnalysis={opencv:report,critic,scene:sc,recommendation:recipe,recipeName:sc.startsWith('Retrato')?'Retrato natural protegido':'Mejora natural inteligente',confidence,at:Date.now()};render(lastAnalysis);status(report.fallback?'Análisis listo · modo compatible':'Análisis profesional listo','ready');return lastAnalysis;
}
function render(a){const e=$('smart-analysis-result');if(!e)return;const c=a.opencv,r=c.regions||{},regions=c.detectedRegions?.length?c.detectedRegions.join(' · '):'General',intensity=Math.round(a.recommendation.adaptiveStrength*100),issues=a.critic.issues.map(x=>`<li><strong>${x.label}</strong><span>${x.advice}</span></li>`).join(''),engine=c.fallback?'Motor local compatible':'OpenCV';e.innerHTML=`<div class="smart-pro-result"><div class="smart-pro-title"><strong>⭐ ${a.recipeName}</strong><small>${a.confidence}% confianza · ${engine}</small></div><div class="smart-metrics smart-metrics-six"><div><small>Escena</small><strong>${a.scene}</strong></div><div><small>Regiones</small><strong>${regions}</strong></div><div><small>Intensidad</small><strong>${intensity}%</strong></div><div><small>Enfoque</small><strong>${c.blurRisk==='low'?'Bueno':c.blurRisk==='medium'?'Medio':'Bajo'}</strong></div><div><small>Ruido</small><strong>${c.noiseEstimate}</strong></div><div><small>Piel protegida</small><strong>${r.face>.02?'Sí':'No aplica'}</strong></div></div><p>${a.critic.summary}</p>${issues?`<ul class="photo-critic-list">${issues}</ul>`:''}<p><strong>Regla:</strong> no resaltar manchas, poros o arrugas y no alterar una zona que ya está bien.</p></div>`;if($('smart-apply'))$('smart-apply').disabled=false;}
function signature(a){return JSON.stringify({at:a.at,recipe:a.recommendation,original:api().state.originalDataUrl?.slice(-48)})}
async function apply(btn){btn.disabled=true;const old=btn.textContent;btn.textContent='Pensando y aplicando la mejor edición…';status('Procesando desde la foto original…','working');try{const a=lastAnalysis||await analyze(),sig=signature(a);if(sig===lastAppliedSignature){api().toast('La mejor mejora ya está aplicada.');status('Mejora ya aplicada','ready');return}let used='local';if(window.PhotoOpenCV?.ready||await window.PhotoOpenCV?.whenReady?.(2500)){const data=await window.PhotoOpenCV.enhanceCurrent(a.recommendation,a.opencv,'original');await api().applyProcessedImageDataUrl(data,true);used='OpenCV';}else{await api().applySmartPixelRecipe(a.recommendation,true);}lastAppliedSignature=sig;renderRecipe(a);api().toast(`Mejora natural aplicada · ${used}`);status('Mejora profesional aplicada','ready')}finally{btn.textContent=old;btn.disabled=false}}
function renderRecipe(a){const e=$('smart-recipe-result');if(!e)return;const r=a.opencv.regions||{},x=a.recommendation;e.hidden=false;e.innerHTML=`<div class="smart-recipe-head"><strong>${a.recipeName}</strong><small>${a.scene} · ${a.confidence}% confianza</small></div><div class="smart-recipe-values"><div><span>Fuerza</span><strong>${Math.round(x.adaptiveStrength*100)}%</strong></div><div><span>Piel</span><strong>${r.face>.02?'Protegida':'No detectada'}</strong></div><div><span>Sombras</span><strong>+${x.shadows}</strong></div><div><span>Claridad facial</span><strong>0</strong></div><div><span>Filtros acumulados</span><strong>No</strong></div></div>`}
async function requireOpenCV(){if(window.PhotoOpenCV?.ready)return true;status('Preparando OpenCV…','working');const ok=await window.PhotoOpenCV?.whenReady?.(15000);if(!ok)throw new Error('OpenCV no pudo cargar. Smart Analysis sí funciona en modo compatible, pero este retoque localizado necesita OpenCV.');return true;}
async function regionalEdit(region,options,label){ensure();await requireOpenCV();status(`Editando solo ${label}…`,'working');const data=await window.PhotoOpenCV.adjustRegion(region,options);await api().applyProcessedImageDataUrl(data,true);api().toast(`${label} corregido; el resto de la foto se conservó`);status('Edición regional aplicada','ready');return true}
async function understand(raw){const t=String(raw||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(/cara|rostro/.test(t)&&/(oscura|muy negra|sin luz|sombra)/.test(t))return regionalEdit('face',{exposure:.25,shadows:22,warmth:2,smooth:true,detail:4,strength:.78},'el rostro');if(/cara|rostro/.test(t)&&/(muy clara|quemada|brillante|sobreexpuesta)/.test(t))return regionalEdit('face',{exposure:-.18,shadows:-4,warmth:0,smooth:true,detail:2,strength:.75},'el rostro');if(/menos cansad|ojeras|cansad/.test(t))return regionalEdit('face',{exposure:.12,shadows:14,warmth:1,smooth:true,detail:3,strength:.68},'el rostro');if(/solo.*fondo|mejora.*fondo/.test(t))return regionalEdit('background',{exposure:.05,shadows:5,detail:5,strength:.62},'el fondo');if(/piel/.test(t)&&/(suav|manchas|arrugas|natural)/.test(t))return regionalEdit('skin',{exposure:.04,shadows:5,warmth:1,smooth:true,detail:0,strength:.64},'la piel');if(/identificacion|credencial|pasaporte|id photo/.test(t)){window.PhotoAIStudio?.enterPortraitIdMode?.();api().toast('Modo identificación preparado con la foto completa.');return true}return false}
const MODE_RECIPES={natural:{exposure:.02,shadows:4,highlights:2,contrast:4,vibrance:5,warmth:1,clarity:2,blackPoint:0,whitePoint:255,gamma:1,denoise:1,label:'Natural'},portrait:{exposure:.04,shadows:6,highlights:3,contrast:2,vibrance:3,warmth:2,clarity:0,blackPoint:0,whitePoint:255,gamma:1,denoise:2,label:'Retrato'},night:{exposure:.18,shadows:18,highlights:8,contrast:6,vibrance:4,warmth:3,clarity:2,blackPoint:0,whitePoint:255,gamma:1,denoise:8,label:'Noche'},document:{exposure:.07,shadows:8,highlights:10,contrast:22,vibrance:-30,warmth:0,clarity:12,blackPoint:3,whitePoint:250,gamma:1,denoise:2,label:'Documento'},vivid:{exposure:.03,shadows:4,highlights:3,contrast:10,vibrance:28,warmth:1,clarity:6,blackPoint:0,whitePoint:255,gamma:1,denoise:1,label:'Vibrante'}};
async function applySmartMode(mode){ensure();const r=MODE_RECIPES[mode];if(!r)return false;document.querySelectorAll('[data-smart-mode]').forEach(b=>b.classList.toggle('active',b.dataset.smartMode===mode));const {label,...recipe}=r;await api().applySmartPixelRecipe(recipe,true);api().toast(`Modo ${label} aplicado desde la foto base`);const hint=$('smart-route-hint');if(hint)hint.textContent=`${label}: edición local aplicada sin acumular ajustes anteriores.`;return true;}
async function runRetouch(btn,label,work,success){ensure();await requireOpenCV();btn.disabled=true;const old=btn.textContent;btn.textContent=label;status('Aplicando retoque localizado…','working');try{const data=await work();await api().applyProcessedImageDataUrl(data,true);api().toast(success);status('Retoque localizado aplicado','ready')}finally{btn.textContent=old;btn.disabled=false}}
function boot(){const a=$('smart-analyze'),b=$('smart-apply'),smooth=$('smart-smooth-skin'),blem=$('smart-remove-blemishes'),moles=$('smart-remove-moles'),slider=$('portrait-strength'),value=$('portrait-strength-value');document.querySelectorAll('[data-smart-mode]').forEach(btn=>btn.onclick=()=>applySmartMode(btn.dataset.smartMode).catch(e=>api()?.toast(e.message)));if($('smart-queue-clear'))$('smart-queue-clear').onclick=()=>{const list=$('smart-queue-list');if(list)list.innerHTML='';if($('smart-queue-count'))$('smart-queue-count').textContent='0';api()?.toast('Lista local vacía')};const updateStrength=()=>{if(value&&slider)value.textContent=`${slider.value}%`};if(slider){slider.oninput=updateStrength;updateStrength()}if(a)a.onclick=()=>analyze().catch(e=>{console.error(e);status('Error de análisis','error');api()?.toast(e.message)});if(b)b.onclick=()=>apply(b).catch(e=>{console.error(e);status('Error al aplicar','error');api()?.toast(e.message)});if(smooth)smooth.onclick=()=>runRetouch(smooth,'Suavizando…',()=>window.PhotoOpenCV.smoothPortraitSkin(Number(slider?.value||35)/100),'Piel suavizada de forma natural').catch(e=>api()?.toast(e.message));if(blem)blem.onclick=()=>runRetouch(blem,'Limpiando…',()=>window.PhotoOpenCV.removeSkinSpots('blemish'),'Granitos y manchas pequeñas reducidos').catch(e=>api()?.toast(e.message));if(moles)moles.onclick=()=>runRetouch(moles,'Retirando…',()=>window.PhotoOpenCV.removeSkinSpots('mole'),'Lunares pequeños retirados').catch(e=>api()?.toast(e.message));const setRetouchDisabled=v=>[smooth,blem,moles].forEach(x=>{if(x)x.disabled=v});document.addEventListener('photoia:image-loaded',()=>{lastAnalysis=null;lastAppliedSignature='';if(b)b.disabled=true;setRetouchDisabled(false);status('Lista para análisis profesional','ready')});document.addEventListener('photoia:image-cleared',()=>{lastAnalysis=null;lastAppliedSignature='';if(b)b.disabled=true;setRetouchDisabled(true);status('Esperando foto…','ready')});window.PhotoSmartCore={version:VERSION,analyze,applyRecommendations:()=>apply(b),understand,regionalEdit,applySmartMode};status('Photo Critic Engine listo','ready')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
