(() => {
'use strict';
const VERSION='11.2.0-regional-vision';
const $=id=>document.getElementById(id),api=()=>window.PhotoIA,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));let lastAnalysis=null;
function status(t,c='ready'){const b=$('smart-core-badge');if(b){b.textContent=t;b.className=`smart-core-badge ${c}`}}
function ensure(){if(!api()?.state?.photo)throw new Error('Abre una foto primero.');}
function fallbackRecipe(cv){const h=cv.histogram||{},r=cv.regions||{};const mid=h.p50??cv.brightness;const exposure=clamp(Math.log2(136/Math.max(48,mid)),-.18,.38);return{exposure:+exposure.toFixed(2),shadows:clamp(Math.round((78-(h.p05||30))*.34),0,26),highlights:clamp(Math.round(((h.p95||220)-218)*.42),0,28),contrast:clamp(Math.round((56-cv.contrast)*.28),-6,14),vibrance:r.skin>.035?9:r.green>.08?14:12,warmth:r.skin>.035?2:0,clarity:cv.blurRisk==='high'?15:cv.blurRisk==='medium'?11:7,blackPoint:clamp(Math.round((h.p05||0)*.22),0,10),whitePoint:clamp(Math.round(255-(255-(h.p95||245))*.18),240,255),gamma:1,denoise:cv.noiseEstimate>18?9:cv.noiseEstimate>11?5:0};}
function scene(cv){const r=cv.regions||{};if(r.skin>.035)return r.green>.08?'Retrato en naturaleza':'Retrato';if(r.green>.14)return'Naturaleza';if(r.sky>.10)return'Exterior';if(cv.brightness<90)return'Poca luz';return'General';}
function quality(cv,recipe){let score=96;score-=cv.clipping?.white?5:0;score-=cv.clipping?.black?5:0;score-=Math.max(0,recipe.clarity-18);score-=Math.max(0,Math.abs(recipe.vibrance)-18);score-=Math.abs(recipe.exposure)>.4?5:0;return clamp(Math.round(score),60,96);}
async function analyze(){ensure();status('OpenCV separa y analiza regiones…','working');const el=$('smart-analysis-result');if(el)el.innerHTML='<div class="smart-progress-list"><span>✓ Histograma y rango tonal</span><span>✓ Piel y rostro aproximado</span><span>✓ Cielo y vegetación</span><span>✓ Ruido, enfoque y detalle</span><span>✓ Horizonte y geometría</span><span class="working">● Diseñando ajustes por región…</span></div>';
 const cv=window.PhotoOpenCV?.ready?await window.PhotoOpenCV.analyzeCurrent():null;if(!cv)throw new Error('OpenCV no está listo.');const sc=scene(cv),recipe=fallbackRecipe(cv),confidence=quality(cv,recipe);lastAnalysis={opencv:cv,scene:sc,recommendation:recipe,recipeName:'Regional Professional Enhance',confidence,at:Date.now()};render(lastAnalysis);status('Mejora regional lista','ready');return lastAnalysis;}
function render(a){const e=$('smart-analysis-result');if(!e)return;const c=a.opencv,r=c.regions||{},regions=c.detectedRegions?.length?c.detectedRegions.join(' · '):'General';e.innerHTML=`<div class="smart-pro-result"><div class="smart-pro-title"><strong>⭐ ${a.recipeName}</strong><small>${a.confidence}% confianza</small></div><div class="smart-metrics smart-metrics-six"><div><small>Escena</small><strong>${a.scene}</strong></div><div><small>Regiones</small><strong>${regions}</strong></div><div><small>Enfoque</small><strong>${c.blurRisk==='low'?'Bueno':c.blurRisk==='medium'?'Medio':'Bajo'}</strong></div><div><small>Ruido</small><strong>${c.noiseEstimate}</strong></div><div><small>Cielo</small><strong>${Math.round((r.sky||0)*100)}%</strong></div><div><small>Piel/verde</small><strong>${Math.round((r.skin||0)*100)}% / ${Math.round((r.green||0)*100)}%</strong></div></div><p>PHOTO IA protegerá la piel, recuperará el cielo y realzará la vegetación con ajustes distintos para cada región.</p></div>`;$('smart-apply').disabled=false;}
async function apply(btn){btn.disabled=true;const old=btn.textContent;btn.textContent='Aplicando mejora regional…';status('Procesando regiones…','working');try{const a=lastAnalysis||await analyze();const data=await window.PhotoOpenCV.enhanceCurrent(a.recommendation,a.opencv);await api().applyProcessedImageDataUrl(data,true);renderRecipe(a);api().toast('Regional Professional Enhance aplicado');status('Mejora regional aplicada','ready')}finally{btn.textContent=old;btn.disabled=false}}
function renderRecipe(a){const e=$('smart-recipe-result');if(!e)return;const r=a.opencv.regions||{};e.hidden=false;e.innerHTML=`<div class="smart-recipe-head"><strong>${a.recipeName}</strong><small>${a.scene} · ${a.confidence}% confianza</small></div><div class="smart-recipe-values"><div><span>Piel</span><strong>${r.skin>.035?'Protegida':'No detectada'}</strong></div><div><span>Cielo</span><strong>${r.sky>.07?'Recuperado':'No detectado'}</strong></div><div><span>Vegetación</span><strong>${r.green>.08?'Realzada':'No detectada'}</strong></div><div><span>Ruido</span><strong>${a.recommendation.denoise}</strong></div><div><span>Detalle</span><strong>${a.recommendation.clarity}</strong></div><div><span>Color global</span><strong>+${a.recommendation.vibrance}</strong></div></div>`;}
function boot(){const a=$('smart-analyze'),b=$('smart-apply');if(a)a.onclick=()=>analyze().catch(e=>{console.error(e);status('Error de análisis','error');api()?.toast(e.message)});if(b)b.onclick=()=>apply(b).catch(e=>{console.error(e);status('Error al aplicar','error');api()?.toast(e.message)});document.addEventListener('photoia:image-loaded',()=>{lastAnalysis=null;if(b)b.disabled=true;status('Lista para analizar regiones','ready')});document.addEventListener('photoia:image-cleared',()=>{lastAnalysis=null;if(b)b.disabled=true;status('Esperando foto…','ready')});window.PhotoSmartCore={version:VERSION,analyze,applyRecommendations:()=>apply(b)};status('Regional Vision Engine listo','ready');}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
