(() => {
'use strict';
const VERSION='13.0';
const categoryMap={
 home:['.command-panel','.quick-actions'],smart:['.smart-core-panel','.vision-panel'],adjust:['.tools','.transform'],
 create:['.creative-panel','#object-inspector','.layers-panel'],ai:['#ai-studio'],export:['.export']
};
const $=id=>document.getElementById(id);

function button(icon,label,id){const b=document.createElement('button');b.type='button';b.className='pro-dock-item';b.id=id;b.innerHTML=`<span>${icon}</span><small class="pro-dock-label">${label}</small>`;b.setAttribute('aria-label',label);return b}
function createCard(icon,title,copy,action){const b=document.createElement('button');b.type='button';b.className='module-card';b.innerHTML=`<span>${icon}</span><div><strong>${title}</strong><small>${copy}</small></div>`;if(action)b.addEventListener('click',action);return b}

function initAdaptiveWorkspace(){
 const main=document.querySelector('.app-shell > main'),workspace=main?.querySelector('.workspace'),oldTabs=$('studio-tabs'),modeToolbar=$('mode-toolbar');
 if(!main||!workspace||!oldTabs||!modeToolbar)return;
 document.body.classList.add('photoia-pro-ui','photoia-modern-ui','photoia-adaptive-ui');main.classList.add('pro-stage');
 const allPanels=[...main.querySelectorAll(':scope > section.panel')],toolPanels=allPanels.filter(p=>p!==workspace);
 const stage=document.createElement('div');stage.className='pro-editor-stage';main.insertBefore(stage,main.firstChild);stage.appendChild(workspace);
 const sheet=document.createElement('aside');sheet.className='pro-tool-sheet';sheet.id='pro-tool-sheet';sheet.hidden=true;sheet.dataset.snap='medium';sheet.innerHTML=`
  <div class="sheet-grabber" aria-hidden="true"></div><div class="pro-sheet-head"><div><small>PHOTO IA ${VERSION}</small><strong id="pro-sheet-title">Herramientas</strong></div>
  <div class="sheet-actions"><button id="sheet-size" type="button" aria-label="Cambiar tamaño">↕</button><button id="pro-sheet-close" type="button" aria-label="Cerrar panel">×</button></div></div>
  <div id="pro-create-tools" class="pro-create-tools" hidden><span>Herramientas</span></div><div id="pro-sheet-content" class="pro-sheet-content"></div>`;
 document.body.appendChild(sheet);const content=$('pro-sheet-content'),createTools=$('pro-create-tools');toolPanels.forEach(p=>{p.classList.add('pro-tool-panel');content.appendChild(p)});
 const dock=document.createElement('nav');dock.className='pro-dock pro-dock-left';dock.setAttribute('aria-label','Módulos de PHOTO IA');document.body.appendChild(dock);
 const nav=[...oldTabs.querySelectorAll('[data-studio-tab]')],titles={home:'Inicio',smart:'Smart',adjust:'Ajustes',create:'Crear',ai:'Alienware',export:'Guardar'};
 nav.forEach(b=>{b.classList.remove('studio-tab');b.classList.add('pro-dock-item','pro-nav-item');b.querySelector('small')?.classList.add('pro-dock-label');dock.appendChild(b)});oldTabs.remove();
 const modes=[...modeToolbar.querySelectorAll('[data-canvas-mode]')],erase=modes.find(b=>b.dataset.canvasMode==='erase'),createModes=modes.filter(b=>b!==erase);
 createModes.forEach(b=>{b.classList.remove('mode-tool','active');b.classList.add('pro-create-tool');createTools.appendChild(b)});modeToolbar.remove();
 if(erase){erase.remove();}
 // Useful main modules only.
 const clean=button('🧽','Limpiar','dock-clean'),select=button('🎯','Selección IA','dock-select'),history=button('📚','Historial','dock-history'),inspect=button('🔍','Inspector IA','dock-inspector'),share=button('📤','Compartir','dock-share'),lab=button('🧪','Lab','dock-lab'),compare=button('◐','Antes/Después','dock-compare');
 [clean,select,history,inspect,share,lab,compare].forEach(b=>dock.appendChild(b));compare.disabled=true;
 const originalCompare=$('compare-btn');compare.addEventListener('pointerdown',()=>originalCompare?.dispatchEvent(new PointerEvent('pointerdown')));['pointerup','pointerleave','pointercancel'].forEach(ev=>compare.addEventListener(ev,()=>originalCompare?.dispatchEvent(new PointerEvent(ev))));
 const sync=()=>compare.disabled=originalCompare?.disabled??true;if(originalCompare)new MutationObserver(sync).observe(originalCompare,{attributes:true});sync();

 Object.entries(categoryMap).forEach(([cat,sels])=>sels.forEach(sel=>content.querySelectorAll(sel).forEach(p=>p.dataset.studioCategory=cat)));toolPanels.forEach(p=>{if(!p.dataset.studioCategory)p.dataset.studioCategory='home'});
 let active=null,timer=null;
 const pulse=b=>{dock.querySelectorAll('.peek').forEach(x=>x.classList.remove('peek'));b?.classList.add('peek');clearTimeout(timer);timer=setTimeout(()=>b?.classList.remove('peek'),1500)};
 const clearCustom=()=>content.querySelectorAll('.custom-module').forEach(x=>x.remove());
 function showSheet(title){$('pro-sheet-title').textContent=title;sheet.hidden=false;document.body.classList.add('pro-sheet-open');requestLayout()}
 function openCategory(cat,trigger){clearCustom();active=cat;toolPanels.forEach(p=>p.hidden=p.dataset.studioCategory!==cat);nav.forEach(b=>b.classList.toggle('active',b.dataset.studioTab===cat));createTools.hidden=cat!=='create';showSheet(titles[cat]||'Herramientas');pulse(trigger)}
 function custom(title,node,trigger){toolPanels.forEach(p=>p.hidden=true);createTools.hidden=true;nav.forEach(b=>b.classList.remove('active'));clearCustom();node.classList.add('custom-module');content.prepend(node);showSheet(title);pulse(trigger)}
 nav.forEach(b=>b.addEventListener('click',e=>{e.preventDefault();const cat=b.dataset.studioTab;if(!sheet.hidden&&active===cat){close();return}openCategory(cat,b)}));
 function close(){sheet.hidden=true;document.body.classList.remove('pro-sheet-open');dock.querySelectorAll('.active').forEach(b=>b.classList.remove('active'));requestLayout()}
 $('pro-sheet-close').onclick=close;$('sheet-size').onclick=()=>{sheet.dataset.snap=sheet.dataset.snap==='compact'?'medium':sheet.dataset.snap==='medium'?'full':'compact';requestLayout()};

 clean.onclick=()=>custom('Limpiar y proyecto',buildClean(),clean);
 select.onclick=()=>custom('Selección IA',buildSelection(),select);
 history.onclick=()=>custom('Historial',buildHistory(),history);
 inspect.onclick=()=>custom('Inspector IA',buildInspector(),inspect);
 share.onclick=()=>custom('Compartir y exportar',buildShare(),share);
 lab.onclick=()=>custom('Laboratorio',buildLab(),lab);

 function buildClean(){const n=document.createElement('section');n.className='module-grid-wrap';n.innerHTML='<p class="module-intro">Limpia la imagen, administra el proyecto o comienza con otra fotografía.</p><div class="module-grid"></div>';const g=n.querySelector('.module-grid');
  g.append(createCard('🪄','Eliminar objeto','Marca un área y envíala a Alienware',()=>{openCategory('ai');window.PhotoIA?.toast('Describe el objeto que quieres eliminar.')}),createCard('👤','Eliminar persona','Usa Selección IA y Alienware',()=>{window.PhotoSegmentation?.segmentPerson?.();window.PhotoIA?.toast('Persona seleccionada. Usa Alienware para rellenar el fondo.')}),createCard('📝','Eliminar texto','Detectar y reparar texto',()=>{openCategory('ai');window.PhotoIA?.toast('Escribe: elimina el texto de la foto.')}),createCard('🖌','Borrador manual','Borra capas creadas manualmente',()=>{window.PhotoIA?.setCanvasMode?.('erase',{openPanel:true});openCategory('create')}),createCard('↩️','Deshacer','Regresa un paso',()=>window.PhotoIA?.undo?.()),createCard('↪️','Rehacer','Recupera el paso siguiente',()=>window.PhotoIA?.redo?.()),createCard('💾','Guardar cambios','Descarga la imagen actual',()=>window.PhotoIA?.download?.()),createCard('📷','Cambiar foto','Borra la actual y abre otra',()=>document.getElementById('new-photo-btn')?.click()),createCard('🔄','Restaurar original','Quita todas las ediciones',()=>window.PhotoIA?.reset?.()));return n}
 function buildSelection(){const n=document.createElement('section');n.className='module-grid-wrap';n.innerHTML='<p class="module-intro">Selecciona regiones para editar solo lo necesario.</p><div class="module-grid"></div>';const g=n.querySelector('.module-grid');
  g.append(createCard('👤','Persona','Segmentación completa',()=>window.PhotoSegmentation?.segmentPerson?.()),createCard('☝️','Objeto por toque','Toca el objeto en la foto',()=>window.PhotoSegmentation?.beginTapMode?.()),createCard('🙂','Cara','Detecta y selecciona el rostro',async()=>{await window.PhotoVision?.analyze?.();window.PhotoVision?.select?.('cara')}),createCard('🚗','Objetos','Analiza todo lo visible',()=>window.PhotoVision?.analyze?.()),createCard('👁','Mostrar máscara','Visualiza la selección',()=>window.PhotoSegmentation?.showMask?.(true)),createCard('🧹','Limpiar máscara','Elimina la selección actual',()=>window.PhotoSegmentation?.clearMask?.()));return n}
 function buildHistory(){const n=document.createElement('section');n.className='history-module';const h=window.PhotoIA?.state?.history||[];n.innerHTML=`<p class="module-intro">${h.length} estado${h.length===1?'':'s'} guardado${h.length===1?'':'s'}. Toca uno para regresar.</p><div class="history-timeline"></div>`;const list=n.querySelector('.history-timeline');h.forEach((json,i)=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<span>${i===0?'📷':'✦'}</span><div><strong>${i===0?'Original / inicio':`Edición ${i}`}</strong><small>${i===h.length-1?'Estado actual':'Toca para restaurar'}</small></div>`;b.onclick=()=>{window.PhotoIA?.restoreJSON?.(json);window.PhotoIA?.toast(`Restaurado al paso ${i}`)};list.appendChild(b)});if(!h.length)list.innerHTML='<p>Aún no hay historial.</p>';return n}
 function buildInspector(){const n=document.createElement('section');n.className='inspector-module';n.innerHTML='<p class="module-intro">Diagnóstico local de la fotografía.</p><div id="adaptive-inspector-results" class="inspector-results"><p>Pulsa analizar para medir la imagen.</p></div><button class="primary inspector-run">🔍 Analizar ahora</button>';n.querySelector('.inspector-run').onclick=async()=>{const r=n.querySelector('#adaptive-inspector-results');r.innerHTML='<p>Analizando…</p>';try{const c=window.PhotoIA?.getPhotoAnalysisCanvas?.(720);if(!c)throw Error('Abre una foto primero.');const ctx=c.getContext('2d'),d=ctx.getImageData(0,0,c.width,c.height).data;let lum=0,lum2=0,sat=0,dark=0,bright=0;for(let i=0;i<d.length;i+=4){const mx=Math.max(d[i],d[i+1],d[i+2]),mn=Math.min(d[i],d[i+1],d[i+2]),l=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];lum+=l;lum2+=l*l;sat+=mx?((mx-mn)/mx):0;if(l<25)dark++;if(l>235)bright++}const px=d.length/4,mean=lum/px,std=Math.sqrt(Math.max(0,lum2/px-mean*mean));r.innerHTML=`<div class="metric-grid"><div><strong>${c.width}×${c.height}</strong><small>Análisis</small></div><div><strong>${Math.round(mean)}</strong><small>Luz media</small></div><div><strong>${Math.round(std)}</strong><small>Contraste</small></div><div><strong>${Math.round(sat/px*100)}%</strong><small>Saturación</small></div><div><strong>${(dark/px*100).toFixed(1)}%</strong><small>Sombras cerradas</small></div><div><strong>${(bright/px*100).toFixed(1)}%</strong><small>Luces altas</small></div></div>`}catch(e){r.innerHTML=`<p>${e.message}</p>`}};return n}
 function buildShare(){const n=document.createElement('section');n.className='module-grid-wrap';n.innerHTML='<p class="module-intro">Guarda, comparte o elige el formato desde el módulo de exportación.</p><div class="module-grid"></div>';const g=n.querySelector('.module-grid');g.append(createCard('💾','Guardar imagen','Descargar con la calidad elegida',()=>window.PhotoIA?.download?.()),createCard('📤','Compartir','Abrir hoja de compartir del teléfono',async()=>{try{const url=window.PhotoIA?.exportDataUrl?.();const blob=await(await fetch(url)).blob();const f=new File([blob],'PHOTO-IA.jpg',{type:blob.type});if(navigator.share&&navigator.canShare?.({files:[f]}))await navigator.share({files:[f],title:'PHOTO IA'});else window.PhotoIA?.download?.()}catch(e){window.PhotoIA?.download?.()}}),createCard('⚙️','Formato y calidad','Abrir opciones avanzadas',()=>openCategory('export')));return n}
 function buildLab(){const n=document.createElement('section');n.className='module-grid-wrap';n.innerHTML='<p class="module-intro">Herramientas experimentales. Las funciones estables se moverán a sus módulos principales.</p><div class="module-grid"></div>';const g=n.querySelector('.module-grid');g.append(createCard('🧬','Segmentación avanzada','Selecciona por toque o persona',()=>custom('Selección IA',buildSelection(),select)),createCard('🖥️','Pruebas Alienware','Diagnóstico del servidor privado',()=>openCategory('ai')),createCard('🧠','Vision Lab','Detección de objetos y caras',()=>window.PhotoVision?.analyze?.()));return n}

 // Adaptive Workspace Engine
 const root=document.documentElement;
 function requestLayout(){requestAnimationFrame(layout)}
 function layout(){const vv=window.visualViewport,w=Math.round(vv?.width||innerWidth),h=Math.round(vv?.height||innerHeight),land=w>h;let device=w<430?'compact':w<768?'phone':w<1100?'tablet':'desktop';root.dataset.device=device;root.dataset.orientation=land?'landscape':'portrait';root.style.setProperty('--aw-vw',`${w}px`);root.style.setProperty('--aw-vh',`${h}px`);root.style.setProperty('--aw-dock',device==='compact'?'28px':device==='phone'?'32px':device==='tablet'?'42px':'48px');const open=!sheet.hidden,snap=sheet.dataset.snap||'medium';let panel=0;if(open){if(device==='desktop')panel=Math.min(430,Math.round(w*.30));else panel=snap==='compact'?Math.round(h*.27):snap==='full'?Math.round(h*.76):Math.round(h*(land?.42:.46))}root.style.setProperty('--aw-panel-size',`${panel}px`);root.style.setProperty('--aw-canvas-h',`${Math.max(300,h-(device==='desktop'?110:84))}px`);document.body.classList.toggle('aw-landscape',land);document.body.classList.toggle('aw-keyboard',vv?innerHeight-vv.height>140:false);window.dispatchEvent(new CustomEvent('photoia:workspace-layout',{detail:{w,h,device,land,panel}}))}
 window.addEventListener('resize',requestLayout);window.visualViewport?.addEventListener('resize',requestLayout);window.visualViewport?.addEventListener('scroll',requestLayout);new ResizeObserver(requestLayout).observe(document.body);requestLayout();
 document.addEventListener('photoia:image-loaded',()=>{compare.disabled=false;close();requestLayout()});document.addEventListener('photoia:preset-applied',()=>requestLayout());
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initAdaptiveWorkspace,{once:true});else initAdaptiveWorkspace();
})();