(() => {
'use strict';
const VERSION='0.1.0';
const $=id=>document.getElementById(id);
const LABELS={
 person:'persona',bicycle:'bicicleta',car:'automóvil',motorcycle:'motocicleta',airplane:'avión',bus:'autobús',train:'tren',truck:'camión',boat:'barco',
 bird:'ave',cat:'gato',dog:'perro',horse:'caballo',sheep:'oveja',cow:'vaca',elephant:'elefante',bear:'oso',zebra:'cebra',giraffe:'jirafa',
 backpack:'mochila',umbrella:'paraguas',handbag:'bolso',tie:'corbata',suitcase:'maleta',frisbee:'frisbee',skis:'esquís',snowboard:'tabla de nieve',
 'sports ball':'pelota',kite:'cometa','baseball bat':'bate','baseball glove':'guante',skateboard:'patineta',surfboard:'tabla de surf','tennis racket':'raqueta',
 bottle:'botella','wine glass':'copa',cup:'taza',fork:'tenedor',knife:'cuchillo',spoon:'cuchara',bowl:'tazón',banana:'banana',apple:'manzana',sandwich:'sándwich',orange:'naranja',broccoli:'brócoli',carrot:'zanahoria','hot dog':'hot dog',pizza:'pizza',donut:'dona',cake:'pastel',
 chair:'silla',couch:'sofá','potted plant':'planta',bed:'cama','dining table':'mesa',toilet:'inodoro',tv:'televisor',laptop:'laptop',mouse:'mouse',remote:'control',keyboard:'teclado','cell phone':'teléfono',microwave:'microondas',oven:'horno',toaster:'tostador',sink:'fregadero',refrigerator:'refrigerador',book:'libro',clock:'reloj',vase:'florero',scissors:'tijeras','teddy bear':'oso de peluche','hair drier':'secadora','toothbrush':'cepillo',face:'rostro'
};
const state={model:null,loading:false,detections:[],visible:true,sourceSignature:'',faceSupported:'FaceDetector' in window};
const api=()=>window.PhotoIA;
const normalize=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function status(text,kind=''){const el=$('vision-status');if(!el)return;el.textContent=text;el.className=`vision-status ${kind}`.trim();}
function photoReady(){return !!api()?.state?.photo;}
function updateButtons(){const ready=photoReady();['vision-analyze','vision-show','vision-hide','vision-clear'].forEach(id=>{const el=$(id);if(el)el.disabled=!ready||(id!=='vision-analyze'&&!state.detections.length)});}
function removeOverlays(){const canvas=api()?.state?.canvas;if(!canvas)return;canvas.getObjects().filter(o=>o.layerType==='vision-detection').forEach(o=>canvas.remove(o));canvas.discardActiveObject();canvas.requestRenderAll();api().renderLayers?.();}
function clear(){removeOverlays();state.detections=[];state.sourceSignature='';renderResults();status('Sin análisis');updateButtons();}
function setVisible(show){state.visible=show;const canvas=api()?.state?.canvas;if(!canvas)return;canvas.getObjects().filter(o=>o.layerType==='vision-detection').forEach(o=>o.visible=show);canvas.requestRenderAll();status(show?'Detecciones visibles':'Detecciones ocultas',show?'ready':'');}
function colorFor(cls){if(cls==='person')return '#f97316';if(cls==='face')return '#ec4899';if(['car','truck','bus','motorcycle','bicycle'].includes(cls))return '#3b82f6';if(['dog','cat','bird','horse'].includes(cls))return '#22c55e';return '#a855f7';}
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.decoding='async';img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('No pude leer la imagen'));img.src=src;});}
async function loadModel(){if(state.model)return state.model;if(state.loading)return new Promise((resolve,reject)=>{const timer=setInterval(()=>{if(state.model){clearInterval(timer);resolve(state.model)}else if(!state.loading){clearInterval(timer);reject(new Error('No se pudo cargar el modelo'))}},100)});state.loading=true;status('Cargando modelo de visión…','loading');try{if(!window.tf||!window.cocoSsd)throw new Error('Las bibliotecas de visión no cargaron. Revisa internet.');await tf.ready();state.model=await cocoSsd.load({base:'lite_mobilenet_v2'});status('Vision Engine listo','ready');return state.model;}finally{state.loading=false;}}
function sourceSignature(){const s=api().state;return `${s.originalDataUrl.length}:${s.photo?.angle||0}:${s.photo?.flipX||false}`;}
function mapBox(box,imgW,imgH){const p=api().state.photo;const left=p.left-p.getScaledWidth()/2,top=p.top-p.getScaledHeight()/2;const sx=p.getScaledWidth()/imgW,sy=p.getScaledHeight()/imgH;return {left:left+box[0]*sx,top:top+box[1]*sy,width:box[2]*sx,height:box[3]*sy};}
function addOverlay(det,index){const canvas=api().state.canvas;const c=colorFor(det.class);const box=mapBox(det.bbox,det.imageWidth,det.imageHeight);const rect=new fabric.Rect({left:0,top:0,width:box.width,height:box.height,fill:'rgba(0,0,0,0.02)',stroke:c,strokeWidth:3,rx:6,ry:6,originX:'left',originY:'top'});const labelText=`${LABELS[det.class]||det.class} ${Math.round(det.score*100)}%`;const label=new fabric.Text(labelText,{left:4,top:4,fontSize:Math.max(12,Math.min(18,box.width/10)),fontWeight:'bold',fill:'#fff',backgroundColor:c,originX:'left',originY:'top'});const group=new fabric.Group([rect,label],{left:box.left,top:box.top,originX:'left',originY:'top',selectable:true,evented:true,hasRotatingPoint:false,lockScalingFlip:true});group.layerId=`vision-${Date.now()}-${index}`;group.layerName=`Detección: ${LABELS[det.class]||det.class}`;group.layerType='vision-detection';group.visionClass=det.class;group.visionLabel=LABELS[det.class]||det.class;group.visionScore=det.score;group.visionIndex=index;group.userLocked=false;canvas.add(group);canvas.bringToFront(group);return group;}
async function detectFaces(img){if(!state.faceSupported)return [];try{const detector=new FaceDetector({fastMode:true,maxDetectedFaces:10});const faces=await detector.detect(img);return faces.map(f=>({class:'face',score:1,bbox:[f.boundingBox.x,f.boundingBox.y,f.boundingBox.width,f.boundingBox.height]}));}catch(err){console.warn('FaceDetector no disponible',err);return [];}}
async function analyze(){if(!photoReady())return api().toast('Abre una foto primero.');if((api().state.photo.angle||0)%360!==0)return api().toast('Para analizar con precisión, gira la foto a su posición original.');api().processing(true,'Analizando la fotografía…');status('Analizando objetos…','loading');try{const model=await loadModel();const img=await loadImage(api().state.originalDataUrl);const max=720,ratio=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));const work=document.createElement('canvas');work.width=Math.max(1,Math.round(img.naturalWidth*ratio));work.height=Math.max(1,Math.round(img.naturalHeight*ratio));work.getContext('2d').drawImage(img,0,0,work.width,work.height);const [objects,faces]=await Promise.all([model.detect(work,20,.45),detectFaces(work)]);removeOverlays();const merged=[...objects,...faces].map(d=>({...d,imageWidth:work.width,imageHeight:work.height}));state.detections=merged.map((d,i)=>({...d,index:i,overlay:addOverlay(d,i)}));state.sourceSignature=sourceSignature();state.visible=true;api().state.canvas.requestRenderAll();api().renderLayers?.();renderResults();status(merged.length?`${merged.length} detección${merged.length===1?'':'es'} encontrada${merged.length===1?'':'s'}`:'No encontré objetos con suficiente confianza',merged.length?'ready':'warn');api().toast(merged.length?'Análisis terminado':'No encontré objetos claros');updateButtons();}catch(err){console.error(err);status(err.message||'Error de visión','error');api().toast('No pude analizar la foto. Revisa la conexión e inténtalo otra vez.');}finally{api().processing(false);}}
function groupedCounts(){return state.detections.reduce((m,d)=>{const key=LABELS[d.class]||d.class;m[key]=(m[key]||0)+1;return m;},{});}
function renderResults(){const host=$('vision-results');if(!host)return;host.innerHTML='';const counts=groupedCounts();const entries=Object.entries(counts);$('vision-count').textContent=`${state.detections.length} detectado${state.detections.length===1?'':'s'}`;if(!entries.length){host.innerHTML='<p class="vision-empty">Abre una foto y pulsa “Analizar foto”.</p>';return;}entries.forEach(([label,count])=>{const row=document.createElement('button');row.type='button';row.className='vision-result';row.innerHTML=`<span>${label}</span><strong>${count}</strong>`;row.onclick=()=>select(label);host.appendChild(row);});}
function find(query){const q=normalize(query);let cls=null;for(const [key,value] of Object.entries(LABELS)){const v=normalize(value);if(q.includes(v)||q.includes(normalize(key))){cls=key;break;}}if(!cls){if(/persona|hombre|mujer|muchacho|muchacha/.test(q))cls='person';else if(/cara|rostro/.test(q))cls='face';else if(/auto|carro|coche|vehiculo/.test(q))cls='car';else if(/perro/.test(q))cls='dog';else if(/gato/.test(q))cls='cat';}
 const matches=cls?state.detections.filter(d=>d.class===cls):state.detections;return matches.sort((a,b)=>b.score-a.score);}
function select(query){if(!state.detections.length){api().toast('Primero analiza la foto.');return false;}const matches=find(query);if(!matches.length){api().toast('No encontré ese objeto en el análisis.');return false;}setVisible(true);const canvas=api().state.canvas;const objects=matches.map(d=>d.overlay).filter(Boolean);const active=objects.length===1?objects[0]:new fabric.ActiveSelection(objects,{canvas});canvas.setActiveObject(active);canvas.requestRenderAll();api().renderLayers?.();status(`${objects.length} ${objects.length===1?'objeto seleccionado':'objetos seleccionados'}`,'ready');return true;}
function command(raw){const t=normalize(raw);if(/analiza|detecta|que hay|que ves|muestrame lo que encontro/.test(t)){analyze();return true;}if(/oculta.*deteccion|oculta.*recuadro/.test(t)){setVisible(false);return true;}if(/muestra.*deteccion|ensen[a|e].*deteccion|resalta.*detect/.test(t)){setVisible(true);return true;}if(/borra.*deteccion|limpia.*deteccion|quita.*recuadro/.test(t)){clear();return true;}if(/selecciona|elige|marca|resalta/.test(t)&&/(persona|rostro|cara|auto|carro|perro|gato|objeto|detect)/.test(t)){select(t);return true;}return false;}
function boot(){const btn=$('vision-analyze');if(!btn)return;btn.onclick=analyze;$('vision-show').onclick=()=>setVisible(true);$('vision-hide').onclick=()=>setVisible(false);$('vision-clear').onclick=clear;renderResults();status('Modelo se carga al usarlo');updateButtons();const canvas=api().state.canvas;canvas.on('object:added',e=>{if(e.target?.photoRole==='main'){clear();setTimeout(updateButtons,0);}});canvas.on('object:removed',updateButtons);setInterval(updateButtons,1000);if(window.PhotoBrain?.register){window.PhotoBrain.register({name:'vision',score:t=>/analiza|detecta|que ves|selecciona (?:la )?(?:persona|cara|rostro|auto|carro|perro|gato)|oculta.*deteccion|muestra.*deteccion/.test(t)?150:0,run:t=>command(t)});}}
window.PhotoVision={version:VERSION,analyze,clear,setVisible,select,find,get detections(){return state.detections},command};
let started=false;function safeBoot(){if(started)return;if(window.PhotoIA?.state?.canvas){started=true;boot()}else setTimeout(safeBoot,100)}window.addEventListener('photoia-ready',safeBoot,{once:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',safeBoot,{once:true});else safeBoot();
})();
